package org.koitharu.kotatsu.kotatsumigration.data

import android.content.Context
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.coroutines.withContext
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import org.koitharu.kotatsu.R
import org.koitharu.kotatsu.core.util.ext.printStackTraceDebug
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Predefined mapping of legacy Kotatsu parser source names (the `MangaParserSource` enum
 * constant strings stored in Kotatsu backups, e.g. `MANGADEX`, `WEBTOONS_EN`) to their
 * equivalent installed Mihon source. The table is baked into `res/raw/kotatsu_source_map.json`,
 * auto-generated by matching the kotatsu-parsers(-redo) source list against the keiyoushi
 * extension index (primarily by website domain). See scratchpad/build_map.py.
 *
 * Keying by the raw backup string (not by this app's own parser enum) is deliberate: different
 * Kotatsu forks ship different parser forks, so the source name in a backup may not exist in
 * DropSauce's own `MangaParserSource`. The table is the single source of truth and is trivially
 * extensible — append entries for additional forks' sources.
 */
@Singleton
class KotatsuSourceMap @Inject constructor(
	@ApplicationContext private val context: Context,
) {

	private val mutex = Mutex()
	@Volatile
	private var tables: Tables? = null

	/** Resolve a legacy Kotatsu source name (e.g. `MANGADEX`) to its Mihon target. */
	suspend fun resolve(sourceName: String): MihonTarget? {
		return load().byName[sourceName.trim().uppercase()]
	}

	/**
	 * Reverse lookup by Mihon source id. Used to surface "recommended to install" extensions for
	 * `MIHON_<id>` library entries whose extension isn't installed (the id is in the asset because
	 * the entry was produced by this migration).
	 */
	suspend fun resolveById(sourceId: Long): MihonTarget? {
		return load().byId[sourceId]
	}

	private suspend fun load(): Tables {
		tables?.let { return it }
		return mutex.withLock {
			tables?.let { return it }
			val parsed = withContext(Dispatchers.IO) { parse() }
			tables = parsed
			parsed
		}
	}

	private fun parse(): Tables = try {
		val raw = context.resources.openRawResource(R.raw.kotatsu_source_map).use { stream ->
			stream.readBytes().toString(Charsets.UTF_8)
		}
		val file = json.decodeFromString(SourceMapFile.serializer(), raw)
		val byName = LinkedHashMap<String, MihonTarget>(file.entries.size)
		val byId = LinkedHashMap<Long, MihonTarget>(file.entries.size)
		for ((enumName, entry) in file.entries) {
			val id = entry.id.toLongOrNull() ?: continue
			val target = MihonTarget(
				sourceId = id,
				sourceName = entry.name,
				packageName = entry.pkg,
			)
			byName[enumName.uppercase()] = target
			// Many Kotatsu enums can map to one Mihon id (language variants); first wins.
			byId.putIfAbsent(id, target)
		}
		Tables(byName, byId)
	} catch (e: Exception) {
		e.printStackTraceDebug()
		Tables(emptyMap(), emptyMap())
	}

	private class Tables(
		val byName: Map<String, MihonTarget>,
		val byId: Map<Long, MihonTarget>,
	)

	private companion object {
		val json = Json { ignoreUnknownKeys = true }
	}

	@Serializable
	private class SourceMapFile(
		@SerialName("entries") val entries: Map<String, Entry> = emptyMap(),
	)

	@Serializable
	private class Entry(
		@SerialName("id") val id: String,
		@SerialName("name") val name: String = "",
		@SerialName("pkg") val pkg: String = "",
	)
}

/** The installed Mihon source a legacy Kotatsu source maps to. */
data class MihonTarget(
	/** Mihon `CatalogueSource.id`; resolve the running source via `MihonExtensionManager.getById`. */
	val sourceId: Long,
	/** Display name of the Mihon source, for reporting (e.g. "MangaDex"). */
	val sourceName: String,
	/** Extension package name, so we can recommend installing the matching extension. */
	val packageName: String,
)
